### PR TITLE
Do not depend on lodash

### PR DESCRIPTION
**Pull request by neg3ntropy**
It's working for us in production.

### CODE REVIEW

**Comment by RickEyre** [comment]
Can this possible get merged + published? It would fix the vulnerability issue in #48.

**Comment by mnutsch** [comment]
Is there any update on this? It looks like this pull request was created back in July. Thanks!

**Comment by neg3ntropy** [comment]
@mnutsch and all. I released [cfsign](https://github.com/tierratelematics/cfsign). Check it out!

**Comment by mnutsch** [comment]
Thanks @neg3ntropy! 

We found yesterday that the AWS SDK recently added a feature to address our original use of this module.

**Comment by neg3ntropy** [comment]
@mnutsch That is not so new actually, it just never mentioned in the docs or anywhere else! So I guess that both this and cfsign are completely irrelevant then.

**Pull request closed without merging**
